/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SessionValidationRequest } from '../../models/session-validation-request';
import { SessionValidationResponse } from '../../models/session-validation-response';

export interface Validate$Params {
      body: SessionValidationRequest
}

export function validate(http: HttpClient, rootUrl: string, params: Validate$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionValidationResponse>> {
  const rb = new RequestBuilder(rootUrl, validate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SessionValidationResponse>;
    })
  );
}

validate.PATH = '/api/v1/internal/sessions/validate';
