#!/usr/bin/env bash
set -euo pipefail

# ─── Configurable variables ──────────────────────────────────────────────────
REGISTRY=""                          # e.g. "registry.example.com/myorg" (leave empty for no prefix)
IMAGE_BACKEND="connecting-backend"
IMAGE_FRONTEND="connecting-frontend"
TAG="latest"
CONTAINER_BACKEND="connecting-backend"
CONTAINER_FRONTEND="connecting-frontend"
PORT_BACKEND=8082
PORT_FRONTEND=4200
COMPOSE_DIR="."
# ─────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$SCRIPT_DIR/wac/backend"
FRONTEND_DIR="$SCRIPT_DIR/wac/frontend"

# ─── 0. Git pull (always first) ──────────────────────────────────────────────
echo "[$(date '+%H:%M:%S')] Pulling latest changes from origin..."
command -v git >/dev/null 2>&1 || { echo "[ERROR] git not found in PATH"; exit 1; }
git -C "$SCRIPT_DIR" pull --ff-only origin main
echo "[$(date '+%H:%M:%S')] ✓ Repository is up to date"

# ─── Auto-generate .env with strong passwords if missing ─────────────────────
if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
  echo "[deploy] .env not found — generating strong passwords..."
  cat > "$SCRIPT_DIR/.env" <<EOF
# Auto-generated by deploy.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Keep this file secret — never commit it.

POSTGRES_USER=connecting
POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)
POSTGRES_DB=connecting_db

KEYCLOAK_ADMIN_USERNAME=admin
KEYCLOAK_ADMIN_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)
EOF
  echo "[deploy] .env created at $SCRIPT_DIR/.env — save the Keycloak admin password before proceeding."
fi

# Load .env
set -a; source "$SCRIPT_DIR/.env"; set +a

# Generate Keycloak realm JSON from template (substitutes GOOGLE_CLIENT_ID/SECRET)
REALM_TEMPLATE="$SCRIPT_DIR/wac/keycloak/realms/connecting.json.template"
REALM_OUTPUT="$SCRIPT_DIR/wac/keycloak/realms/connecting.json"
[[ -f "$REALM_TEMPLATE" ]] || err "Realm template not found: $REALM_TEMPLATE"
envsubst '${GOOGLE_CLIENT_ID} ${GOOGLE_CLIENT_SECRET}' < "$REALM_TEMPLATE" > "$REALM_OUTPUT"

PUSH=false
ENV="development"

# ─── CLI flags ───────────────────────────────────────────────────────────────
for arg in "$@"; do
  case $arg in
    --push)        PUSH=true ;;
    --env=*)       ENV="${arg#*=}" ;;
    -h|--help)
      echo "Usage: ./deploy.sh [--push] [--env=development|staging|production]"
      exit 0
      ;;
    *)
      echo "[ERROR] Unknown argument: $arg"
      echo "Usage: ./deploy.sh [--push] [--env=development|staging|production]"
      exit 1
      ;;
  esac
done

# ─── Helpers ─────────────────────────────────────────────────────────────────
log()  { echo "[$(date '+%H:%M:%S')] $*"; }
ok()   { echo "[$(date '+%H:%M:%S')] ✓ $*"; }
err()  { echo "[$(date '+%H:%M:%S')] ✗ $*" >&2; exit 1; }

# ─── Preflight checks ────────────────────────────────────────────────────────
log "=== Connecting deploy — env=$ENV ==="

[[ -f "$SCRIPT_DIR/deploy.sh" ]] || err "Must be run from the repo root (deploy.sh not found at $SCRIPT_DIR)"

command -v docker  >/dev/null 2>&1 || err "Docker is not installed or not in PATH"
docker info        >/dev/null 2>&1 || err "Docker daemon is not running"
command -v docker compose >/dev/null 2>&1 || \
  command -v docker-compose >/dev/null 2>&1 || \
  err "docker compose (v2) or docker-compose (v1) is required"

[[ -d "$BACKEND_DIR" ]]  || err "Backend directory not found: $BACKEND_DIR"
[[ -d "$FRONTEND_DIR" ]] || err "Frontend directory not found: $FRONTEND_DIR"

ok "Preflight checks passed"

# ─── Environment-specific overrides ──────────────────────────────────────────
case "$ENV" in
  production)
    TAG="stable"
    log "Production mode: tag=$TAG, push enforced"
    PUSH=true
    ;;
  staging)
    TAG="staging"
    log "Staging mode: tag=$TAG"
    ;;
  development)
    log "Development mode: tag=$TAG"
    ;;
  *)
    err "Unknown --env value '$ENV'. Use: development, staging, production"
    ;;
esac

# Compose the full image names (with optional registry prefix)
if [[ -n "$REGISTRY" ]]; then
  FULL_BACKEND="$REGISTRY/$IMAGE_BACKEND:$TAG"
  FULL_FRONTEND="$REGISTRY/$IMAGE_FRONTEND:$TAG"
else
  FULL_BACKEND="$IMAGE_BACKEND:$TAG"
  FULL_FRONTEND="$IMAGE_FRONTEND:$TAG"
fi

BUILD_FLAGS="--no-cache"

# ─── 1. Infrastructure (Postgres + Keycloak) ─────────────────────────────────
log "Stopping infrastructure containers for rebuild..."
COMPOSE_CMD="docker compose"
command -v docker compose >/dev/null 2>&1 || COMPOSE_CMD="docker-compose"

(cd "$SCRIPT_DIR/$COMPOSE_DIR" && $COMPOSE_CMD down)
ok "Infrastructure stopped"

# Release any containers or processes still holding the required ports
for port in 5433 8180; do
  # Stop Docker containers holding the port
  conflicting=$(docker ps --format '{{.ID}} {{.Ports}}' | grep ":${port}->" | awk '{print $1}' || true)
  if [[ -n "$conflicting" ]]; then
    log "Port $port held by Docker container $conflicting — stopping it..."
    docker stop "$conflicting"
  fi
  # Detect non-Docker processes holding the port and fail clearly
  pid=""
  if command -v fuser >/dev/null 2>&1; then
    pid=$(fuser "${port}/tcp" 2>/dev/null | tr -d ' ' || true)
  elif command -v ss >/dev/null 2>&1; then
    pid=$(ss -tlnp "sport = :${port}" 2>/dev/null | grep -oP 'pid=\K[0-9]+' | head -1 || true)
  fi
  if [[ -n "$pid" ]]; then
    proc=$(ps -p "$pid" -o comm= 2>/dev/null || echo "unknown")
    err "Port $port is held by system process '$proc' (PID $pid). Free it first and re-run deploy.sh."
  fi
done

# Force-remove named infra containers so docker compose always recreates them
# with the correct port mappings from docker-compose.yml (avoids stale containers
# created outside compose that end up without port bindings)
for name in connecting-db keycloak-connecting; do
  if docker ps -a --format '{{.Names}}' | grep -qx "$name"; then
    log "Removing stale container: $name"
    docker rm -f "$name" 2>/dev/null || true
  fi
done

log "Starting infrastructure (PostgreSQL + Keycloak)..."
(cd "$SCRIPT_DIR/$COMPOSE_DIR" && $COMPOSE_CMD up -d)
ok "Infrastructure is up"

# ─── 4. Docker cleanup ───────────────────────────────────────────────────────
log "Cleaning Docker build cache..."
docker builder prune -af
ok "Docker build cache cleared"

# ─── 5. Build backend image ──────────────────────────────────────────────────
log "Building backend image: $FULL_BACKEND ..."
docker build $BUILD_FLAGS \
  -t "$FULL_BACKEND" \
  -f "$BACKEND_DIR/Dockerfile" \
  "$BACKEND_DIR"
ok "Backend image built: $FULL_BACKEND"

# ─── 3. Build frontend image ─────────────────────────────────────────────────
log "Building frontend image: $FULL_FRONTEND ..."
docker build $BUILD_FLAGS \
  -t "$FULL_FRONTEND" \
  -f "$FRONTEND_DIR/Dockerfile" \
  "$FRONTEND_DIR"
ok "Frontend image built: $FULL_FRONTEND"

# ─── 4. Push to registry (optional) ─────────────────────────────────────────
if $PUSH; then
  [[ -n "$REGISTRY" ]] || err "--push requires REGISTRY to be set in deploy.sh"
  log "Pushing images to $REGISTRY ..."
  docker push "$FULL_BACKEND"
  docker push "$FULL_FRONTEND"
  ok "Images pushed to registry"
fi

# ─── 5. Stop and remove existing app containers ──────────────────────────────
for name in "$CONTAINER_BACKEND" "$CONTAINER_FRONTEND"; do
  if docker ps -a --format '{{.Names}}' | grep -qx "$name"; then
    log "Stopping and removing container: $name"
    docker stop "$name" 2>/dev/null || true
    docker rm   "$name" 2>/dev/null || true
  fi
done
ok "Old containers removed"

# ─── 6. Run backend container ────────────────────────────────────────────────
log "Starting backend container on port $PORT_BACKEND ..."
docker run -d \
  --name "$CONTAINER_BACKEND" \
  --network "connecting_connecting" \
  -p "$PORT_BACKEND:8080" \
  -e SPRING_DATASOURCE_URL="jdbc:postgresql://connecting-db:5432/${POSTGRES_DB:-connecting_db}" \
  -e SPRING_DATASOURCE_USERNAME="${POSTGRES_USER:-admin}" \
  -e SPRING_DATASOURCE_PASSWORD="${POSTGRES_PASSWORD:-admin}" \
  -e SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI="https://auth.wacchat.win/realms/connecting" \
  -e KEYCLOAK_ADMIN_URL="http://keycloak-connecting:8080" \
  -e KEYCLOAK_ADMIN_USERNAME="${KEYCLOAK_ADMIN_USERNAME:-admin}" \
  -e KEYCLOAK_ADMIN_PASSWORD="${KEYCLOAK_ADMIN_PASSWORD:-admin}" \
  -e ADMIN_EMAIL="${ADMIN_EMAIL:-}" \
  -v "$SCRIPT_DIR/wac/backend/uploads:/app/uploads" \
  --restart unless-stopped \
  "$FULL_BACKEND"
ok "Backend container started"

# ─── 7. Run frontend container ───────────────────────────────────────────────
log "Starting frontend container on port $PORT_FRONTEND ..."
docker run -d \
  --name "$CONTAINER_FRONTEND" \
  --network "connecting_connecting" \
  -p "$PORT_FRONTEND:80" \
  --restart unless-stopped \
  "$FULL_FRONTEND"
ok "Frontend container started"

# ─── 8. Health check ─────────────────────────────────────────────────────────
log "Waiting for backend to be ready..."
HEALTH_URL="http://localhost:$PORT_BACKEND/actuator/health"
MAX_RETRIES=30
RETRY_INTERVAL=3

healthy=false
for i in $(seq 1 $MAX_RETRIES); do
  http_code=$(curl -s -o /dev/null -w "%{http_code}" "$HEALTH_URL" 2>/dev/null || echo "000")
  if [[ "$http_code" == "200" ]] || [[ "$http_code" == "302" ]] || [[ "$http_code" == "401" ]]; then
    healthy=true
    break
  fi
  echo "  Attempt $i/$MAX_RETRIES — HTTP $http_code (retrying in ${RETRY_INTERVAL}s...)"
  sleep $RETRY_INTERVAL
done

if $healthy; then
  ok "Backend is healthy at $HEALTH_URL"
else
  echo ""
  log "Health check timed out after $((MAX_RETRIES * RETRY_INTERVAL))s — check container logs:"
  echo "  docker logs $CONTAINER_BACKEND"
fi

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Deploy complete — env=$ENV"
echo ""
echo " Backend  : http://localhost:$PORT_BACKEND"
echo " Frontend : http://localhost:$PORT_FRONTEND"
echo " Swagger  : http://localhost:$PORT_BACKEND/swagger-ui.html"
echo " Keycloak : http://localhost:8180"
echo ""
echo " Logs:"
echo "   docker logs -f $CONTAINER_BACKEND"
echo "   docker logs -f $CONTAINER_FRONTEND"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
