#!/usr/bin/env bash
set -euo pipefail

# ─── Configurable variables ──────────────────────────────────────────────────
REGISTRY=""                          # e.g. "registry.example.com/myorg" (leave empty for no prefix)
IMAGE_BACKEND="wacchat-backend"
IMAGE_FRONTEND="wacchat-frontend"
IMAGE_FILE_SERVICE="wacchat-file-service"
IMAGE_API_GATEWAY="wacchat-api-gateway"
TAG="latest"
CONTAINER_BACKEND="wacchat-backend"
CONTAINER_FRONTEND="wacchat-frontend"
CONTAINER_FILE_SERVICE="wacchat-file-service"
CONTAINER_API_GATEWAY="wacchat-api-gateway"
PORT_BACKEND=8082
PORT_FRONTEND=4200
PORT_FILE_SERVICE=8083
PORT_API_GATEWAY=8081
COMPOSE_DIR="."
# ─────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$SCRIPT_DIR/wac/backend"
FRONTEND_DIR="$SCRIPT_DIR/wac/frontend"
FILE_SERVICE_DIR="$SCRIPT_DIR/wac/file-service"
API_GATEWAY_DIR="$SCRIPT_DIR/wac/api-gateway"

# ─── 0. Git pull (always first) ──────────────────────────────────────────────
echo "[$(date '+%H:%M:%S')] Pulling latest changes from origin..."
command -v git >/dev/null 2>&1 || { echo "[ERROR] git not found in PATH"; exit 1; }
git -C "$SCRIPT_DIR" pull --ff-only origin main
echo "[$(date '+%H:%M:%S')] ✓ Repository is up to date"

# ─── Auto-generate .env with strong passwords if missing ─────────────────────
if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
  echo "[deploy] .env not found — generating strong passwords..."
  cat > "$SCRIPT_DIR/.env" <<EOF
# Auto-generated by deploy.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Keep this file secret — never commit it.

POSTGRES_USER=wacchat
POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)
POSTGRES_DB=wacchat_db

KEYCLOAK_ADMIN_USERNAME=admin
KEYCLOAK_ADMIN_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)

FILE_SERVICE_INTERNAL_API_KEY=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)

GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)
EOF
  echo "[deploy] .env created at $SCRIPT_DIR/.env — save the Keycloak admin password before proceeding."
fi

# Load .env
set -a; source "$SCRIPT_DIR/.env"; set +a

# Generate Keycloak realm JSON from template
REALM_TEMPLATE="$SCRIPT_DIR/wac/keycloak/realms/wacchat.json.template"
REALM_OUTPUT="$SCRIPT_DIR/wac/keycloak/realms/wacchat.json"
[[ -f "$REALM_TEMPLATE" ]] || err "Realm template not found: $REALM_TEMPLATE"
_pw_orig="${MAIL_PASSWORD:-}"
if [[ ${#_pw_orig} -eq 16 ]]; then
  MAIL_PASSWORD="${_pw_orig:0:4} ${_pw_orig:4:4} ${_pw_orig:8:4} ${_pw_orig:12:4}"
fi
envsubst '${GOOGLE_CLIENT_ID} ${GOOGLE_CLIENT_SECRET} ${MAIL_USERNAME} ${MAIL_PASSWORD} ${MAIL_FROM}' < "$REALM_TEMPLATE" > "$REALM_OUTPUT"
MAIL_PASSWORD="$_pw_orig"

PUSH=false
ENV="development"

# ─── CLI flags ───────────────────────────────────────────────────────────────
for arg in "$@"; do
  case $arg in
    --push)        PUSH=true ;;
    --env=*)       ENV="${arg#*=}" ;;
    -h|--help)
      echo "Usage: ./deploy.sh [--push] [--env=development|staging|production]"
      exit 0
      ;;
    *)
      echo "[ERROR] Unknown argument: $arg"
      echo "Usage: ./deploy.sh [--push] [--env=development|staging|production]"
      exit 1
      ;;
  esac
done

# ─── Helpers ─────────────────────────────────────────────────────────────────
log()  { echo "[$(date '+%H:%M:%S')] $*"; }
ok()   { echo "[$(date '+%H:%M:%S')] ✓ $*"; }
err()  { echo "[$(date '+%H:%M:%S')] ✗ $*" >&2; exit 1; }

set_keycloak_admin_email() {
  [[ -z "${ADMIN_EMAIL:-}"              ]] && return 0
  [[ -z "${KEYCLOAK_ADMIN_USERNAME:-}"  ]] && return 0
  [[ -z "${KEYCLOAK_ADMIN_PASSWORD:-}"  ]] && return 0
  local kc="http://localhost:8180"
  log "Waiting for Keycloak to be ready..."
  local i=0
  until curl -sf "$kc/realms/master" >/dev/null 2>&1; do
    (( ++i )); if (( i >= 30 )); then log "Keycloak not ready — skipping admin email setup"; return 0; fi
    sleep 2
  done
  local token
  token=$(curl -sf -X POST "$kc/realms/master/protocol/openid-connect/token" \
    --data-urlencode "client_id=admin-cli" \
    --data-urlencode "username=${KEYCLOAK_ADMIN_USERNAME}" \
    --data-urlencode "password=${KEYCLOAK_ADMIN_PASSWORD}" \
    --data-urlencode "grant_type=password" 2>/dev/null \
    | grep -o '"access_token":"[^"]*"' | cut -d'"' -f4) || true
  [[ -z "$token" ]] && { log "Could not get Keycloak token — skipping admin email setup"; return 0; }
  local user_id
  user_id=$(curl -sf "$kc/admin/realms/master/users?username=${KEYCLOAK_ADMIN_USERNAME}" \
    -H "Authorization: Bearer $token" 2>/dev/null \
    | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4) || true
  [[ -z "$user_id" ]] && { log "Admin user not found in Keycloak — skipping email setup"; return 0; }
  curl -sf -X PUT "$kc/admin/realms/master/users/$user_id" \
    -H "Authorization: Bearer $token" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"${ADMIN_EMAIL}\",\"emailVerified\":true}" >/dev/null 2>&1 || true
  ok "Keycloak admin email set to ${ADMIN_EMAIL}"
}

# ─── Preflight checks ────────────────────────────────────────────────────────
log "=== WacChat deploy — env=$ENV ==="

[[ -f "$SCRIPT_DIR/docker-compose.yml" ]] || err "Must be run from the repo root (docker-compose.yml not found at $SCRIPT_DIR)"

command -v docker  >/dev/null 2>&1 || err "Docker is not installed or not in PATH"
docker info        >/dev/null 2>&1 || err "Docker daemon is not running"
command -v docker compose >/dev/null 2>&1 || \
  command -v docker-compose >/dev/null 2>&1 || \
  err "docker compose (v2) or docker-compose (v1) is required"

[[ -d "$BACKEND_DIR" ]]      || err "Backend directory not found: $BACKEND_DIR"
[[ -d "$FRONTEND_DIR" ]]     || err "Frontend directory not found: $FRONTEND_DIR"
[[ -d "$FILE_SERVICE_DIR" ]] || err "File-service directory not found: $FILE_SERVICE_DIR"
[[ -d "$API_GATEWAY_DIR" ]]  || err "API gateway directory not found: $API_GATEWAY_DIR"

ok "Preflight checks passed"

# ─── Environment-specific overrides ──────────────────────────────────────────
case "$ENV" in
  production)
    TAG="stable"
    log "Production mode: tag=$TAG, push enforced"
    PUSH=true
    ;;
  staging)
    TAG="staging"
    log "Staging mode: tag=$TAG"
    ;;
  development)
    log "Development mode: tag=$TAG"
    ;;
  *)
    err "Unknown --env value '$ENV'. Use: development, staging, production"
    ;;
esac

# Compose the full image names (with optional registry prefix)
if [[ -n "$REGISTRY" ]]; then
  FULL_BACKEND="$REGISTRY/$IMAGE_BACKEND:$TAG"
  FULL_FRONTEND="$REGISTRY/$IMAGE_FRONTEND:$TAG"
  FULL_FILE_SERVICE="$REGISTRY/$IMAGE_FILE_SERVICE:$TAG"
  FULL_API_GATEWAY="$REGISTRY/$IMAGE_API_GATEWAY:$TAG"
else
  FULL_BACKEND="$IMAGE_BACKEND:$TAG"
  FULL_FRONTEND="$IMAGE_FRONTEND:$TAG"
  FULL_FILE_SERVICE="$IMAGE_FILE_SERVICE:$TAG"
  FULL_API_GATEWAY="$IMAGE_API_GATEWAY:$TAG"
fi

BUILD_FLAGS="--no-cache"

# ─── 1. Infrastructure (Postgres + Keycloak) ─────────────────────────────────
log "Stopping infrastructure containers for rebuild..."
COMPOSE_CMD="docker compose"
command -v docker compose >/dev/null 2>&1 || COMPOSE_CMD="docker-compose"

# Observability stack depends on the infra network, so stop it first
(cd "$SCRIPT_DIR/$COMPOSE_DIR" && $COMPOSE_CMD -f docker-compose.observability.yml down 2>/dev/null || true)

(cd "$SCRIPT_DIR/$COMPOSE_DIR" && $COMPOSE_CMD down)
ok "Infrastructure stopped"

# Release any containers or processes still holding the required ports
for port in 5433 8180; do
  # Stop Docker containers holding the port
  conflicting=$(docker ps --format '{{.ID}} {{.Ports}}' | grep ":${port}->" | awk '{print $1}' || true)
  if [[ -n "$conflicting" ]]; then
    log "Port $port held by Docker container $conflicting — stopping it..."
    docker stop "$conflicting"
  fi
  # Detect non-Docker processes holding the port and fail clearly
  pid=""
  if command -v fuser >/dev/null 2>&1; then
    pid=$(fuser "${port}/tcp" 2>/dev/null | tr -d ' ' || true)
  elif command -v ss >/dev/null 2>&1; then
    pid=$(ss -tlnp "sport = :${port}" 2>/dev/null | grep -oP 'pid=\K[0-9]+' | head -1 || true)
  fi
  if [[ -n "$pid" ]]; then
    proc=$(ps -p "$pid" -o comm= 2>/dev/null || echo "unknown")
    err "Port $port is held by system process '$proc' (PID $pid). Free it first and re-run deploy.sh."
  fi
done

# Force-remove named infra containers so docker compose always recreates them
# with the correct port mappings from docker-compose.yml (avoids stale containers
# created outside compose that end up without port bindings)
for name in wacchat-db keycloak-wacchat; do
  if docker ps -a --format '{{.Names}}' | grep -qx "$name"; then
    log "Removing stale container: $name"
    docker rm -f "$name" 2>/dev/null || true
  fi
done

log "Starting infrastructure (PostgreSQL + Keycloak)..."
(cd "$SCRIPT_DIR/$COMPOSE_DIR" && $COMPOSE_CMD up -d)
ok "Infrastructure is up"
set_keycloak_admin_email

# Observability stack needs the network created by the infra compose file
log "Starting observability stack (Prometheus, Grafana, Loki, Tempo)..."
(cd "$SCRIPT_DIR/$COMPOSE_DIR" && $COMPOSE_CMD -f docker-compose.observability.yml up -d)
ok "Observability stack is up"

# ─── 4. Docker cleanup ───────────────────────────────────────────────────────
log "Cleaning Docker build cache..."
docker builder prune -af
ok "Docker build cache cleared"

# ─── 5. Build backend image ──────────────────────────────────────────────────
log "Building backend image: $FULL_BACKEND ..."
docker build $BUILD_FLAGS \
  -t "$FULL_BACKEND" \
  -f "$BACKEND_DIR/Dockerfile" \
  "$BACKEND_DIR"
ok "Backend image built: $FULL_BACKEND"

# ─── 5b. Build file-service image ────────────────────────────────────────────
log "Building file-service image: $FULL_FILE_SERVICE ..."
docker build $BUILD_FLAGS \
  -t "$FULL_FILE_SERVICE" \
  -f "$FILE_SERVICE_DIR/Dockerfile" \
  "$FILE_SERVICE_DIR"
ok "File-service image built: $FULL_FILE_SERVICE"

# ─── 5c. Build api-gateway image ─────────────────────────────────────────────
log "Building api-gateway image: $FULL_API_GATEWAY ..."
docker build $BUILD_FLAGS \
  -t "$FULL_API_GATEWAY" \
  -f "$API_GATEWAY_DIR/Dockerfile" \
  "$API_GATEWAY_DIR"
ok "API gateway image built: $FULL_API_GATEWAY"

# ─── 3. Build frontend image ─────────────────────────────────────────────────
log "Building frontend image: $FULL_FRONTEND ..."
docker build $BUILD_FLAGS \
  -t "$FULL_FRONTEND" \
  -f "$FRONTEND_DIR/Dockerfile" \
  "$FRONTEND_DIR"
ok "Frontend image built: $FULL_FRONTEND"

# ─── 4. Push to registry (optional) ─────────────────────────────────────────
if $PUSH; then
  [[ -n "$REGISTRY" ]] || err "--push requires REGISTRY to be set in deploy.sh"
  log "Pushing images to $REGISTRY ..."
  docker push "$FULL_BACKEND"
  docker push "$FULL_FRONTEND"
  docker push "$FULL_FILE_SERVICE"
  docker push "$FULL_API_GATEWAY"
  ok "Images pushed to registry"
fi

# ─── 5. Stop and remove existing app containers ──────────────────────────────
for name in "$CONTAINER_BACKEND" "$CONTAINER_FRONTEND" "$CONTAINER_FILE_SERVICE" "$CONTAINER_API_GATEWAY"; do
  if docker ps -a --format '{{.Names}}' | grep -qx "$name"; then
    log "Stopping and removing container: $name"
    docker stop "$name" 2>/dev/null || true
    docker rm   "$name" 2>/dev/null || true
  fi
done
ok "Old containers removed"

# ─── 6a. Run file-service container ──────────────────────────────────────────
log "Starting file-service container on port $PORT_FILE_SERVICE ..."
docker run -d \
  --name "$CONTAINER_FILE_SERVICE" \
  --network "wacchat_wacchat" \
  -p "$PORT_FILE_SERVICE:8080" \
  -e R2_ACCOUNT_ID="${R2_ACCOUNT_ID:-}" \
  -e R2_ACCESS_KEY_ID="${R2_ACCESS_KEY_ID:-}" \
  -e R2_SECRET_ACCESS_KEY="${R2_SECRET_ACCESS_KEY:-}" \
  -e R2_BUCKET_NAME="${R2_BUCKET_NAME:-}" \
  -e R2_PUBLIC_BASE_URL="${R2_PUBLIC_BASE_URL:-}" \
  -e FILE_SERVICE_INTERNAL_API_KEY="${FILE_SERVICE_INTERNAL_API_KEY:-}" \
  -e OTLP_TRACING_ENDPOINT="http://wacchat-tempo:4318/v1/traces" \
  -e LOKI_URL="http://wacchat-loki:3100/loki/api/v1/push" \
  -e TRACING_SAMPLING_PROBABILITY="${TRACING_SAMPLING_PROBABILITY:-1.0}" \
  --restart unless-stopped \
  "$FULL_FILE_SERVICE"
ok "File-service container started"

# ─── 6b. Run backend container ───────────────────────────────────────────────
log "Starting backend container on port $PORT_BACKEND ..."
docker run -d \
  --name "$CONTAINER_BACKEND" \
  --network "wacchat_wacchat" \
  -p "$PORT_BACKEND:8080" \
  -e SPRING_DATASOURCE_URL="jdbc:postgresql://wacchat-db:5432/${POSTGRES_DB:-wacchat_db}" \
  -e SPRING_DATASOURCE_USERNAME="${POSTGRES_USER:-admin}" \
  -e SPRING_DATASOURCE_PASSWORD="${POSTGRES_PASSWORD:-admin}" \
  -e KEYCLOAK_ISSUER_URI="https://auth.wacchat.win/realms/wacchat" \
  -e KEYCLOAK_ADMIN_URL="http://keycloak-wacchat:8080" \
  -e KEYCLOAK_ADMIN_USERNAME="${KEYCLOAK_ADMIN_USERNAME:-admin}" \
  -e KEYCLOAK_ADMIN_PASSWORD="${KEYCLOAK_ADMIN_PASSWORD:-admin}" \
  -e ADMIN_EMAIL="${ADMIN_EMAIL:-}" \
  -e MAIL_USERNAME="${MAIL_USERNAME:-}" \
  -e MAIL_PASSWORD="${MAIL_PASSWORD:-}" \
  -e MAIL_FROM="${MAIL_FROM:-}" \
  -e FILE_SERVICE_BASE_URL="http://wacchat-file-service:8080" \
  -e FILE_SERVICE_INTERNAL_API_KEY="${FILE_SERVICE_INTERNAL_API_KEY:-}" \
  -e OTLP_TRACING_ENDPOINT="http://wacchat-tempo:4318/v1/traces" \
  -e LOKI_URL="http://wacchat-loki:3100/loki/api/v1/push" \
  -e TRACING_SAMPLING_PROBABILITY="${TRACING_SAMPLING_PROBABILITY:-1.0}" \
  -v "$SCRIPT_DIR/wac/backend/uploads:/app/uploads" \
  --restart unless-stopped \
  "$FULL_BACKEND"
ok "Backend container started"

# ─── 6c. Run api-gateway container ───────────────────────────────────────────
log "Starting api-gateway container on port $PORT_API_GATEWAY ..."
docker run -d \
  --name "$CONTAINER_API_GATEWAY" \
  --network "wacchat_wacchat" \
  -p "$PORT_API_GATEWAY:$PORT_API_GATEWAY" \
  -e BACKEND_BASE_URL="http://wacchat-backend:$PORT_BACKEND" \
  -e FILE_SERVICE_BASE_URL="http://wacchat-file-service:$PORT_FILE_SERVICE" \
  -e OTLP_TRACING_ENDPOINT="http://wacchat-tempo:4318/v1/traces" \
  -e LOKI_URL="http://wacchat-loki:3100/loki/api/v1/push" \
  -e TRACING_SAMPLING_PROBABILITY="${TRACING_SAMPLING_PROBABILITY:-1.0}" \
  --restart unless-stopped \
  "$FULL_API_GATEWAY"
ok "API gateway container started"

# ─── 7. Run frontend container ───────────────────────────────────────────────
log "Starting frontend container on port $PORT_FRONTEND ..."
docker run -d \
  --name "$CONTAINER_FRONTEND" \
  --network "wacchat_wacchat" \
  -p "$PORT_FRONTEND:80" \
  --restart unless-stopped \
  "$FULL_FRONTEND"
ok "Frontend container started"

# ─── 8. Health check ─────────────────────────────────────────────────────────
log "Waiting for backend to be ready..."
HEALTH_URL="http://localhost:$PORT_BACKEND/actuator/health"
MAX_RETRIES=30
RETRY_INTERVAL=3

healthy=false
for i in $(seq 1 $MAX_RETRIES); do
  http_code=$(curl -s -o /dev/null -w "%{http_code}" "$HEALTH_URL" 2>/dev/null || echo "000")
  if [[ "$http_code" == "200" ]] || [[ "$http_code" == "302" ]] || [[ "$http_code" == "401" ]]; then
    healthy=true
    break
  fi
  echo "  Attempt $i/$MAX_RETRIES — HTTP $http_code (retrying in ${RETRY_INTERVAL}s...)"
  sleep $RETRY_INTERVAL
done

if $healthy; then
  ok "Backend is healthy at $HEALTH_URL"
else
  echo ""
  log "Health check timed out after $((MAX_RETRIES * RETRY_INTERVAL))s — check container logs:"
  echo "  docker logs $CONTAINER_BACKEND"
fi

# ─── 8b. API gateway health check ────────────────────────────────────────────
log "Waiting for API gateway to be ready..."
GATEWAY_HEALTH_URL="http://localhost:$PORT_API_GATEWAY/actuator/health"

gateway_healthy=false
for i in $(seq 1 $MAX_RETRIES); do
  http_code=$(curl -s -o /dev/null -w "%{http_code}" "$GATEWAY_HEALTH_URL" 2>/dev/null || echo "000")
  if [[ "$http_code" == "200" ]]; then
    gateway_healthy=true
    break
  fi
  echo "  Attempt $i/$MAX_RETRIES — HTTP $http_code (retrying in ${RETRY_INTERVAL}s...)"
  sleep $RETRY_INTERVAL
done

if $gateway_healthy; then
  ok "API gateway is healthy at $GATEWAY_HEALTH_URL"
else
  echo ""
  log "API gateway health check timed out after $((MAX_RETRIES * RETRY_INTERVAL))s — check container logs:"
  echo "  docker logs $CONTAINER_API_GATEWAY"
fi

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Deploy complete — env=$ENV"
echo ""
echo " API Gateway  : http://localhost:$PORT_API_GATEWAY"
echo " Backend      : http://localhost:$PORT_BACKEND"
echo " Frontend     : http://localhost:$PORT_FRONTEND"
echo " File-service : http://localhost:$PORT_FILE_SERVICE"
echo " Swagger      : http://localhost:$PORT_BACKEND/swagger-ui.html"
echo " Keycloak     : http://localhost:8180"
echo " Grafana      : http://localhost:3000"
echo " Prometheus   : http://localhost:9090"
echo ""
echo " Logs:"
echo "   docker logs -f $CONTAINER_API_GATEWAY"
echo "   docker logs -f $CONTAINER_BACKEND"
echo "   docker logs -f $CONTAINER_FRONTEND"
echo "   docker logs -f $CONTAINER_FILE_SERVICE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
