services:
  prometheus:
    volumes:
      - ./observability/prometheus/prometheus.local.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
