apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-uid
    type: prometheus
    access: proxy
    url: http://wacchat-prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    uid: loki-uid
    type: loki
    access: proxy
    url: http://wacchat-loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo-uid
          matcherRegex: 'traceId=(\w+)'
          name: TraceID
          url: '$${__value.raw}'
    editable: false

  - name: Tempo
    uid: tempo-uid
    type: tempo
    access: proxy
    url: http://wacchat-tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki-uid
        filterByTraceID: true
      serviceMap:
        datasourceUid: prometheus-uid
    editable: false
