spring:
  banner:
    location: classpath:banner/banner.txt
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/connecting_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/connecting}
          audiences:
            - connecting-app
  servlet:
    multipart:
      max-file-size: 50MB

management:
  health:
    mail:
      enabled: false

springdoc:
  default-produces-media-type: application/json


application:
  file:
    uploads:
      media-output-path: ./uploads
  keycloak:
    admin-url: ${KEYCLOAK_ADMIN_URL:http://keycloak-connecting:8080}
    realm: connecting
    admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
  cleanup:
    inactivity-days: 21
    protected-email: ${ADMIN_EMAIL:}