services:
  postgres:
    container_name: connecting-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB:-connecting_db}
    ports:
      - 5433:5432
    networks:
      - connecting
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    container_name: keycloak-connecting
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 8180:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME:-gpradmin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: auth.wacchat.win
      KC_HOSTNAME_STRICT: false
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
    networks:
      - connecting
    volumes:
      - ../keycloak/realms:/opt/keycloak/data/import
    command:
      - "start-dev"
      - "--import-realm"

networks:
  connecting:
    driver: bridge

volumes:
  postgres:
    driver: local
