/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { acceptChat } from '../fn/chat/accept-chat';
import { AcceptChat$Params } from '../fn/chat/accept-chat';
import { ChatResponse } from '../models/chat-response';
import { createChat } from '../fn/chat/create-chat';
import { CreateChat$Params } from '../fn/chat/create-chat';
import { getChatsByReceiver } from '../fn/chat/get-chats-by-receiver';
import { GetChatsByReceiver$Params } from '../fn/chat/get-chats-by-receiver';
import { rejectChat } from '../fn/chat/reject-chat';
import { RejectChat$Params } from '../fn/chat/reject-chat';
import { StringResponse } from '../models/string-response';
import { toggleFavorite } from '../fn/chat/toggle-favorite';
import { ToggleFavorite$Params } from '../fn/chat/toggle-favorite';

@Injectable({ providedIn: 'root' })
export class ChatService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getChatsByReceiver()` */
  static readonly GetChatsByReceiverPath = '/api/v1/chats';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getChatsByReceiver()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChatsByReceiver$Response(params?: GetChatsByReceiver$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChatResponse>>> {
    return getChatsByReceiver(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getChatsByReceiver$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChatsByReceiver(params?: GetChatsByReceiver$Params, context?: HttpContext): Observable<Array<ChatResponse>> {
    return this.getChatsByReceiver$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ChatResponse>>): Array<ChatResponse> => r.body)
    );
  }

  /** Path part for operation `createChat()` */
  static readonly CreateChatPath = '/api/v1/chats';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createChat()` instead.
   *
   * This method doesn't expect any request body.
   */
  createChat$Response(params: CreateChat$Params, context?: HttpContext): Observable<StrictHttpResponse<StringResponse>> {
    return createChat(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createChat$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  createChat(params: CreateChat$Params, context?: HttpContext): Observable<StringResponse> {
    return this.createChat$Response(params, context).pipe(
      map((r: StrictHttpResponse<StringResponse>): StringResponse => r.body)
    );
  }

  /** Path part for operation `rejectChat()` */
  static readonly RejectChatPath = '/api/v1/chats/{chatId}/reject';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rejectChat()` instead.
   *
   * This method doesn't expect any request body.
   */
  rejectChat$Response(params: RejectChat$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return rejectChat(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rejectChat$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rejectChat(params: RejectChat$Params, context?: HttpContext): Observable<void> {
    return this.rejectChat$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `toggleFavorite()` */
  static readonly ToggleFavoritePath = '/api/v1/chats/{chatId}/favorite';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `toggleFavorite()` instead.
   *
   * This method doesn't expect any request body.
   */
  toggleFavorite$Response(params: ToggleFavorite$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: boolean;
}>> {
    return toggleFavorite(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `toggleFavorite$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  toggleFavorite(params: ToggleFavorite$Params, context?: HttpContext): Observable<{
[key: string]: boolean;
}> {
    return this.toggleFavorite$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: boolean;
}>): {
[key: string]: boolean;
} => r.body)
    );
  }

  /** Path part for operation `acceptChat()` */
  static readonly AcceptChatPath = '/api/v1/chats/{chatId}/accept';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `acceptChat()` instead.
   *
   * This method doesn't expect any request body.
   */
  acceptChat$Response(params: AcceptChat$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return acceptChat(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `acceptChat$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  acceptChat(params: AcceptChat$Params, context?: HttpContext): Observable<void> {
    return this.acceptChat$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
