/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ChatValidationResponse } from '../models/chat-validation-response';
import { validate1 } from '../fn/chat-validation-controller/validate-1';
import { Validate1$Params } from '../fn/chat-validation-controller/validate-1';

@Injectable({ providedIn: 'root' })
export class ChatValidationControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `validate1()` */
  static readonly Validate1Path = '/api/v1/internal/chats/validate';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `validate1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  validate1$Response(params: Validate1$Params, context?: HttpContext): Observable<StrictHttpResponse<ChatValidationResponse>> {
    return validate1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `validate1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  validate1(params: Validate1$Params, context?: HttpContext): Observable<ChatValidationResponse> {
    return this.validate1$Response(params, context).pipe(
      map((r: StrictHttpResponse<ChatValidationResponse>): ChatValidationResponse => r.body)
    );
  }

}
