/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addMember } from '../fn/group-chat/add-member';
import { AddMember$Params } from '../fn/group-chat/add-member';
import { ChatResponse } from '../models/chat-response';
import { createGroup } from '../fn/group-chat/create-group';
import { CreateGroup$Params } from '../fn/group-chat/create-group';
import { GroupMemberResponse } from '../models/group-member-response';
import { listMembers } from '../fn/group-chat/list-members';
import { ListMembers$Params } from '../fn/group-chat/list-members';
import { removeMember } from '../fn/group-chat/remove-member';
import { RemoveMember$Params } from '../fn/group-chat/remove-member';
import { renameGroup } from '../fn/group-chat/rename-group';
import { RenameGroup$Params } from '../fn/group-chat/rename-group';

@Injectable({ providedIn: 'root' })
export class GroupChatService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listMembers()` */
  static readonly ListMembersPath = '/api/v1/chats/{chatId}/members';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listMembers()` instead.
   *
   * This method doesn't expect any request body.
   */
  listMembers$Response(params: ListMembers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GroupMemberResponse>>> {
    return listMembers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listMembers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listMembers(params: ListMembers$Params, context?: HttpContext): Observable<Array<GroupMemberResponse>> {
    return this.listMembers$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GroupMemberResponse>>): Array<GroupMemberResponse> => r.body)
    );
  }

  /** Path part for operation `addMember()` */
  static readonly AddMemberPath = '/api/v1/chats/{chatId}/members';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addMember()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addMember$Response(params: AddMember$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return addMember(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addMember$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addMember(params: AddMember$Params, context?: HttpContext): Observable<void> {
    return this.addMember$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `createGroup()` */
  static readonly CreateGroupPath = '/api/v1/chats/groups';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createGroup()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createGroup$Response(params: CreateGroup$Params, context?: HttpContext): Observable<StrictHttpResponse<ChatResponse>> {
    return createGroup(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createGroup$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createGroup(params: CreateGroup$Params, context?: HttpContext): Observable<ChatResponse> {
    return this.createGroup$Response(params, context).pipe(
      map((r: StrictHttpResponse<ChatResponse>): ChatResponse => r.body)
    );
  }

  /** Path part for operation `renameGroup()` */
  static readonly RenameGroupPath = '/api/v1/chats/{chatId}/name';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `renameGroup()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  renameGroup$Response(params: RenameGroup$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return renameGroup(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `renameGroup$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  renameGroup(params: RenameGroup$Params, context?: HttpContext): Observable<void> {
    return this.renameGroup$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `removeMember()` */
  static readonly RemoveMemberPath = '/api/v1/chats/{chatId}/members/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeMember()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeMember$Response(params: RemoveMember$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return removeMember(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeMember$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeMember(params: RemoveMember$Params, context?: HttpContext): Observable<void> {
    return this.removeMember$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
