/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { postSystemMessage } from '../fn/internal-system-message-controller/post-system-message';
import { PostSystemMessage$Params } from '../fn/internal-system-message-controller/post-system-message';

@Injectable({ providedIn: 'root' })
export class InternalSystemMessageControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `postSystemMessage()` */
  static readonly PostSystemMessagePath = '/api/v1/internal/messages/system';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postSystemMessage()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postSystemMessage$Response(params: PostSystemMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return postSystemMessage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postSystemMessage$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postSystemMessage(params: PostSystemMessage$Params, context?: HttpContext): Observable<void> {
    return this.postSystemMessage$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
