/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BlockedUserResponse } from '../models/blocked-user-response';
import { blockUser } from '../fn/moderation/block-user';
import { BlockUser$Params } from '../fn/moderation/block-user';
import { getBlockedUsers } from '../fn/moderation/get-blocked-users';
import { GetBlockedUsers$Params } from '../fn/moderation/get-blocked-users';
import { reportUser } from '../fn/moderation/report-user';
import { ReportUser$Params } from '../fn/moderation/report-user';
import { unblockUser } from '../fn/moderation/unblock-user';
import { UnblockUser$Params } from '../fn/moderation/unblock-user';

@Injectable({ providedIn: 'root' })
export class ModerationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `reportUser()` */
  static readonly ReportUserPath = '/api/v1/users/{id}/report';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportUser$Response(params: ReportUser$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return reportUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportUser(params: ReportUser$Params, context?: HttpContext): Observable<void> {
    return this.reportUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `blockUser()` */
  static readonly BlockUserPath = '/api/v1/users/{id}/block';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `blockUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  blockUser$Response(params: BlockUser$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return blockUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `blockUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  blockUser(params: BlockUser$Params, context?: HttpContext): Observable<void> {
    return this.blockUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `unblockUser()` */
  static readonly UnblockUserPath = '/api/v1/users/{id}/block';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `unblockUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  unblockUser$Response(params: UnblockUser$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return unblockUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `unblockUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  unblockUser(params: UnblockUser$Params, context?: HttpContext): Observable<void> {
    return this.unblockUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getBlockedUsers()` */
  static readonly GetBlockedUsersPath = '/api/v1/users/blocked';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getBlockedUsers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBlockedUsers$Response(params?: GetBlockedUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BlockedUserResponse>>> {
    return getBlockedUsers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getBlockedUsers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBlockedUsers(params?: GetBlockedUsers$Params, context?: HttpContext): Observable<Array<BlockedUserResponse>> {
    return this.getBlockedUsers$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<BlockedUserResponse>>): Array<BlockedUserResponse> => r.body)
    );
  }

}
