/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { SessionValidationResponse } from '../models/session-validation-response';
import { validate } from '../fn/session-validation-controller/validate';
import { Validate$Params } from '../fn/session-validation-controller/validate';

@Injectable({ providedIn: 'root' })
export class SessionValidationControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `validate()` */
  static readonly ValidatePath = '/api/v1/internal/sessions/validate';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `validate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  validate$Response(params: Validate$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionValidationResponse>> {
    return validate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `validate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  validate(params: Validate$Params, context?: HttpContext): Observable<SessionValidationResponse> {
    return this.validate$Response(params, context).pipe(
      map((r: StrictHttpResponse<SessionValidationResponse>): SessionValidationResponse => r.body)
    );
  }

}
