/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ChatResponse } from '../models/chat-response';
import { getOrCreateReportBugChat } from '../fn/support/get-or-create-report-bug-chat';
import { GetOrCreateReportBugChat$Params } from '../fn/support/get-or-create-report-bug-chat';

@Injectable({ providedIn: 'root' })
export class SupportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getOrCreateReportBugChat()` */
  static readonly GetOrCreateReportBugChatPath = '/api/v1/support/report-bug-chat';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOrCreateReportBugChat()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrCreateReportBugChat$Response(params?: GetOrCreateReportBugChat$Params, context?: HttpContext): Observable<StrictHttpResponse<ChatResponse>> {
    return getOrCreateReportBugChat(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOrCreateReportBugChat$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrCreateReportBugChat(params?: GetOrCreateReportBugChat$Params, context?: HttpContext): Observable<ChatResponse> {
    return this.getOrCreateReportBugChat$Response(params, context).pipe(
      map((r: StrictHttpResponse<ChatResponse>): ChatResponse => r.body)
    );
  }

}
