/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChatValidationRequest } from '../../models/chat-validation-request';
import { ChatValidationResponse } from '../../models/chat-validation-response';

export interface Validate1$Params {
      body: ChatValidationRequest
}

export function validate1(http: HttpClient, rootUrl: string, params: Validate1$Params, context?: HttpContext): Observable<StrictHttpResponse<ChatValidationResponse>> {
  const rb = new RequestBuilder(rootUrl, validate1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChatValidationResponse>;
    })
  );
}

validate1.PATH = '/api/v1/internal/chats/validate';
