/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChatResponse {
  archived?: boolean;
  avatarUrl?: string;
  favorite?: boolean;
  id?: string;
  lastMessage?: string;
  lastMessageTime?: string;
  lastMessageType?: 'TEXT' | 'IMAGE' | 'VIDEO' | 'AUDIO';
  name?: string;
  pendingMessageCount?: number;
  receiverId?: string;
  recipientOnline?: boolean;
  senderId?: string;
  status?: 'PENDING' | 'ACCEPTED' | 'REJECTED';
  unreadCount?: number;
}
