/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChatResponse {
  avatarUrl?: string;
  id?: string;
  lastMessage?: string;
  lastMessageTime?: string;
  name?: string;
  pendingMessageCount?: number;
  receiverId?: string;
  recipientOnline?: boolean;
  senderId?: string;
  status?: 'PENDING' | 'ACCEPTED' | 'REJECTED';
  unreadCount?: number;
}
