/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GroupMemberResponse } from '../models/group-member-response';
export interface ChatResponse {
  adminChat?: boolean;
  archived?: boolean;
  avatarUrl?: string;
  favorite?: boolean;
  id?: string;
  lastMessage?: string;
  lastMessageTime?: string;
  lastMessageType?: 'TEXT' | 'IMAGE' | 'VIDEO' | 'AUDIO';
  members?: Array<GroupMemberResponse>;
  name?: string;
  pendingMessageCount?: number;
  receiverId?: string;
  recipientOnline?: boolean;
  senderId?: string;
  status?: 'PENDING' | 'ACCEPTED' | 'REJECTED';
  type?: 'DIRECT' | 'GROUP';
  unreadCount?: number;
}
