/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GroupMemberResponse {
  avatarUrl?: string;
  name?: string;
  online?: boolean;
  role?: 'OWNER' | 'MEMBER';
  userId?: string;
}
