/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReactionSummaryResponse } from '../models/reaction-summary-response';
export interface MessageResponse {
  content?: string;
  createdAt?: string;
  deleted?: boolean;
  editedAt?: string;
  forwarded?: boolean;
  id?: number;
  media?: Array<string>;
  reactions?: Array<ReactionSummaryResponse>;
  receiverId?: string;
  replyToId?: number;
  senderId?: string;
  starred?: boolean;
  state?: 'SENT' | 'SEEN';
  type?: 'TEXT' | 'IMAGE' | 'VIDEO' | 'AUDIO';
}
