/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageRequest {
  chatId: string;
  content?: string;
  forwarded?: boolean;
  replyToId?: number;
  type: 'TEXT' | 'IMAGE' | 'VIDEO' | 'AUDIO';
}
