/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReactionSummaryResponse {
  count?: number;
  emoji?: string;
  reactedByMe?: boolean;
}
