/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SystemMessageRequest {
  chatId?: string;
  content?: string;
  receiverId?: string;
  senderId?: string;
}
